week08/day02/DatabaseIntegration/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseIntegration.Models
{
    public class ToDo
    {
        [Key]
        public long Id { get; set; }
        public string Title { get; set; }
        public bool IsUrgent { get; set; }
        public bool IsDone { get; set; }
    }
}

week08/day02/DatabaseIntegration/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DatabaseIntegration.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseIntegration.Controllers
{
    [Route("/")]
    public class ToDoController : Controller
    {
        private readonly ApplicationContext applicationContext;

        public ToDoController(ApplicationContext applicationContext)
        {
            this.applicationContext = applicationContext;
        }

        [Route("/")]
        [HttpGet("/list")]
        public IActionResult List(bool isActive)
        {
            // Create a SQL query in the background
            var todos = applicationContext.Todos.ToList();
            if (isActive)
            {
                return View(todos.Where(t => !t.IsDone).ToList());
            }
            return View(todos);
        }

        [HttpGet("/AddToDo")]
        public IActionResult AddToDo()
        {
            return View();
        }

        [HttpPost("/AddToDo")]
        public IActionResult AddToDo(ToDo newTodo)
        {
            using (var context = applicationContext)
            {
                context.Todos.Add(newTodo);
                context.SaveChanges();
            }
            return RedirectToAction("List");
        }

        [HttpGet("/RemoveToDo")]
        public IActionResult RemoveToDo(long id)
        {
            using (var context = applicationContext)
            {
                context.Todos.Remove(context.Todos.Find(id));
                context.SaveChanges();
                return RedirectToAction("List");
            }
        }

        [HttpGet("/{id}/edit")]
        public IActionResult EditToDo([FromRoute] long id)
        {
            using (var context = applicationContext)
            {
                ToDo currentToDo = context.Todos.Find(id);
                return View(currentToDo);
            }
        }

        [HttpPost("/{id}/edit")]
        public IActionResult SaveToDo([FromRoute] long id, string title, bool isDone, bool isUrgent)
        {
            using (var context = applicationContext)
            {
                ToDo updateToDo = context.Todos.Find(id);
                updateToDo.Title = title;
                updateToDo.IsDone = isDone;
                updateToDo.IsUrgent = isUrgent;
                context.Todos.Update(updateToDo);
                context.SaveChanges();
            }
            return RedirectToAction("List");
        }

        [HttpGet("/search")]
        public IActionResult SearchToDo(string title)
        {
            using(var context = applicationContext)
            {
                if (title == null)
                {
                    return RedirectToAction("List");
                }
                var todos = applicationContext.Todos.ToList();
                return View("List", todos.Where(t => t.Title.ToLower().Contains(title)));
            }
        }

        /*[HttpGet("/edit")]
        public IActionResult EditTodo(long id)
        {
            using (var context = applicationContext)
            {
                ViewData["id"] = id;
                ToDo currentTodo = context.Todos.Find(id);
                ViewData["currentTodo"] = currentTodo.Title;
                return View();
            }
        }

        [HttpPost("/edit")]
        public IActionResult SaveToDo(long id, string title, bool isDone, bool isUrgent)
        {
            using (var context = applicationContext)
            {
                ToDo updateTodo = context.Todos.Find(id);
                updateTodo.Title = title;
                updateTodo.IsDone = isDone;
                updateTodo.IsUrgent = isUrgent;
                context.Todos.Update(updateTodo);
                context.SaveChanges();
            }
            return RedirectToAction("List");
        }*/





        

        /*public List<ToDo> Todos { get; set; } = new List<ToDo>
        {
            new ToDo { Title = "start the day" },
            new ToDo { Title = "Finish H2 workshop 1" },
            new ToDo { Title = "Finish JPA workshop 2" },
            new ToDo { Title = "Create a CRUD project" }
        };

        [HttpGet("")]
        [HttpGet("list")]
        public IActionResult List()
        {
            return View(Todos);
        }*/
    }
}

week08/day02/DatabaseIntegration/Views/ToDo/AddToDo.cshtml
<h1>Add new todo</h1>

<form method="post" action="AddToDo">
    <label for="title">Name</label>
    <input id="title" name="title" type="text" />
    <label for="isUrgent">Is Urgent?</label>
    <select name="isUrgent">
        <option value="true">Yes</option>
        <option value="false">No</option>
    </select>
    <button type="submit">Add</button>
</form>

week08/day02/DatabaseIntegration/Views/ToDo/EditToDo.cshtml
@model DatabaseIntegration.Models.ToDo

<h1>Edit Todo</h1>

<form method="post" action="@Url.Action("SaveToDo","ToDo", new { id = Model.Id })">
    <label for="title">Todo Name</label>
    <input id="title" name="title" type="text" value="@Model.Title" />

    <label for="IsUrgent">Urgent</label>
    @Html.EditorFor(m => m.IsUrgent)
    <label for="IsDone">Done</label>
    @Html.EditorFor(m => m.IsDone)

    <button type="submit">Submit</button>
</form>

week08/day02/DatabaseIntegration/Views/ToDo/List.cshtml
<h1>Todos for today:</h1>

<form method="get" action="/search">
    <input name="title" type="text" />
    <button type="submit">Search</button>
</form>

@Html.ActionLink("Add todo", "AddToDo")
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>TITLE</th>
            <th>URGENT</th>
            <th>DONE</th>
        </tr>
    </thead>
    
    @foreach (var todo in Model)
    {
<tr>
    <td>@todo.Id</td>
    <td>@todo.Title</td>
    <td>@todo.IsUrgent</td>
    <td>@todo.IsDone</td>
    <td>@Html.ActionLink("Remove", "RemoveToDo", "todo", new { id = todo.Id })</td>
    <td>@Html.ActionLink("Edit", "EditToDo", "todo", new { id = todo.Id })</td>
</tr>
    }
</table>
@Html.ActionLink("Show active", "List", "ToDo", new { isActive = true })